### ISSUE TITLE
Invalid parameter type

### ISSUE THREAD

**Issue by ThweThweSoe** [aussieBIMguru/Dynamo_Scripts#1]
Hi 
While I  try to add a few parameters to a single family,
i still don't understand why it comes up the error with "Invalid parameter type"
I've tried to solve out as per issues  #72 & #73, but it does not work for me.
 
Dynamo version-2.3.0.7661
Revit Version 2020.2
Orchid-230.01.7410
Thanks In advance,

**Comment by ThweThweSoe** [comment]
attached my note and excel file

[test.zip](https://github.com/aussieBIMguru/Dynamo_Scripts/files/4521346/test.zip)

**Comment by aussieBIMguru** [comment]
Use PG_TEXT instead of PG_Text

**Comment by ThweThweSoe** [comment]
Thank You so much for your advice, got it.
